#!/bin/sh

set -eu

cat > /usr/share/nginx/html/runtime-config.js <<EOF
window.__DIASOFT_ENV__ = {
  VITE_GATEWAY_BASE_URL: "${VITE_GATEWAY_BASE_URL:-}",
  VITE_REGISTRY_BASE_URL: "${VITE_REGISTRY_BASE_URL:-}",
  VITE_AUTH_ENABLED: "${VITE_AUTH_ENABLED:-}",
  VITE_OIDC_AUTHORITY: "${VITE_OIDC_AUTHORITY:-}",
  VITE_OIDC_ISSUER: "${VITE_OIDC_ISSUER:-}",
  VITE_OIDC_CLIENT_ID: "${VITE_OIDC_CLIENT_ID:-}",
  VITE_OIDC_REDIRECT_URI: "${VITE_OIDC_REDIRECT_URI:-}",
  VITE_OIDC_POST_LOGOUT_REDIRECT_URI: "${VITE_OIDC_POST_LOGOUT_REDIRECT_URI:-}"
};
EOF
